# Generated by Django 3.1.5 on 2021-01-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210125_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language']},
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
